// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFiles(arg1, arg2) {
  return window['go']['main']['App']['DecryptFiles'](arg1, arg2);
}

export function GetCoverAsBase64(arg1) {
  return window['go']['main']['App']['GetCoverAsBase64'](arg1);
}

export function GetDefaultOutputDir() {
  return window['go']['main']['App']['GetDefaultOutputDir']();
}

export function GetFileSize(arg1) {
  return window['go']['main']['App']['GetFileSize'](arg1);
}

export function SelectNCMFiles() {
  return window['go']['main']['App']['SelectNCMFiles']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}
