// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DecryptFiles(arg1:Array<string>,arg2:string):Promise<Array<main.DecryptStatus>>;

export function GetCoverAsBase64(arg1:string):Promise<string>;

export function GetDefaultOutputDir():Promise<string>;

export function GetFileSize(arg1:number):Promise<string>;

export function SelectNCMFiles():Promise<Array<main.FileInfo>>;

export function SelectOutputDir():Promise<string>;
