// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function ConvertFiles(arg1, arg2) {
  return window['go']['main']['App']['ConvertFiles'](arg1, arg2);
}

export function GetCoverAsBase64(arg1) {
  return window['go']['main']['App']['GetCoverAsBase64'](arg1);
}

export function GetDefaultOutputDir() {
  return window['go']['main']['App']['GetDefaultOutputDir']();
}

export function GetFileSize(arg1) {
  return window['go']['main']['App']['GetFileSize'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectNCMFiles() {
  return window['go']['main']['App']['SelectNCMFiles']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}
