// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFFmpeg():Promise<boolean>;

export function ConvertFiles(arg1:Array<main.FileConvertRequest>,arg2:string):Promise<Array<main.DecryptStatus>>;

export function GetCoverAsBase64(arg1:string):Promise<string>;

export function GetDefaultOutputDir():Promise<string>;

export function GetFileSize(arg1:number):Promise<string>;

export function GetSettings():Promise<main.AppSettings>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SelectNCMFiles():Promise<Array<main.FileInfo>>;

export function SelectOutputDir():Promise<string>;
